### PR TITLE
2.3.x show message when discount code added

### PR DESCRIPTION
**Pull request by vo1**

### CODE REVIEW

**Comment by crankycyclops** [comment]
Hi,

Thanks for the pull request, but this is a regression and breaks something I spent hours fixing previously. Please see the big block comment in the file you deleted:

```
/*
         * If a valid coupon code was set in the URL, we save a cookie with that
	 * value here so we can remember it when it's time to checkout. Originally,
	 * I was trying to set this value in
	 * Plugin\FrontControllerInterface::beforeDispatch(), but after having weird
	 * issues and tracing through the code in Magento core, I discovered in
	 * \Magento\Framework\App\Http::launch() that I should listen for the
	 * controller_front_send_response_before event and then set cookies there,
	 * because the cookie headers can't be set until after the request has been
	 * dispatched and the response has been fully rendered. I spent many hours
	 * pulling my hair out figuring this out...
*/
```

**Comment by vo1** [comment]
your code doesnt show msg anymore in 2.3 because of the load order. Basically at the step you were pushing message to messageManager it is already rendered in block, so pushing does nothing.

**Comment by crankycyclops** [comment]
> your code doesnt show msg anymore in 2.3 because of the load order. Basically at the step you were pushing message to messageManager it is already rendered in block, so pushing does nothing.

I see. That makes sense as far as setting the message, but I'm pretty sure the cookie itself still can't be set in the FrontController. See the last four lines of `\Magento\Framework\App\Http::launch()`.

I remember during my own testing when developing this module that the cookie would be set in my dev environment, but would not be set in my production environment due to differences in the way cached pages were rendered vs. how the pages were rendered in dev. The issue was ultimately that you couldn't set cookies once the headers have already been sent, and while in dev it happened to work, when using the page cache, it didn't. I can't remember exactly which code I traced through to discover the reason for that issue, but I know the only way I was able to fix it was to listen for controller_front_send_response_before and set the cookie that way.

**Comment by vo1** [comment]
I have tested in incognito mode, and I see discount code cookie is created with my fixes at least in 2.3.5-p2 and is applied as soon as product is added to a cart.

**Comment by vo1** [comment]
The only problem I see now is that the discount is not getting applied if a product is already in cart (but cookie is created). But I guess it is some other issue not related to this commit.

**Comment by crankycyclops** [comment]
> I have tested in incognito mode, and I see discount code cookie is created with my fixes at least in 2.3.5-p2 and is applied as soon as product is added to a cart.

Try the following:

1. Run these commands to put the code into production mode and compile classes and static assets:

```
bin/magento deploy:mode:set production
php bin/magento setup:di:compile
php bin/magento setup:static-content:deploy
```

2. Browse to a url with a discount coupon code. Observe that the cookie is set the first time you browse to that page.

3. Clear your cookies and browse to the same url again. This time, because the page has been cached, a different class is used to render it. This different code path results in the cookie not being set again.

**Comment by crankycyclops** [comment]
I just made a couple of changes to the repo. The first is that I added a version number to composer.json. You don't have to worry about changing this (I'll update it when I'm ready to make a new release), but you'll need to merge master into your branch to pull in the changes. The second is that I created a separate develop branch, where active development will go. After syncing your own branch against master, you'll want to base your changes on develop so that I can merge to that instead of master once the PR is ready. Thank you!

**Comment by crankycyclops** [comment]
Closing due to inactivity.

**Pull request closed without merging**
